[tool.poetry]
name = "mosamatic"
version = "1.0"
description = "A CLI tool for body composition analysis from DICOM CT scans"
authors = ["Ralph Brecheisen <ralph.brecheisen@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "mosamatic" }]

[tool.poetry.dependencies]
python = "^3.11.0"
click = "<8.1.8"

[tool.poetry.scripts]
mosamatic = "mosamatic.main:cli"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"