[tool.poetry]
name = "mosamatic-cli"
version = "1.1.0"
description = "A CLI tool for body composition analysis from DICOM CT scans"
authors = ["Ralph Brecheisen <ralph.brecheisen@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "mosamatic" }]

[tool.poetry.dependencies]
python = "3.11.0"
click = "<8.1.8"
pydicom = "3.0.1"
numpy = "2.3.0"
pendulum = "3.1.0"
pillow = "11.2.1"
python-gdcm = "3.0.25"
torch = "2.7.1"
torchvision = "0.22.1"

[tool.poetry.scripts]
mosamatic = "mosamatic.main:cli"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"

[tool.pytest.ini_options]
addopts = "-s"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"