from mosamatic.tasks.calculatescorestask.calculatescorestask import CalculateScoresTask
from mosamatic.tasks.copyfilestask.copyfilestask import CopyFilesTask
from mosamatic.tasks.createpngsfromsegmentationstask.createpngsfromsegmentationstask import CreatePngsFromSegmentationsTask
from mosamatic.tasks.decompressdicomfilestask.decompressdicomfilestask import DecompressDicomFilesTask
from mosamatic.tasks.rescaledicomfilestask.rescaledicomfilestask import RescaleDicomFilesTask
from mosamatic.tasks.segmentmusclefatl3task.segmentmusclefatl3task import SegmentMuscleFatL3Task
from mosamatic.tasks.segmentmusclefatl3tensorflowtask.segmentmusclefatl3tensorflowtask import SegmentMuscleFatL3TensorFlowTask