from mosamatic.tasks.decompressdicomfilestask.decompressdicomfilestask import DecompressDicomFilesTask
from mosamatic.tasks.dummytask.dummytask import DummyTask
from mosamatic.tasks.segmentmusclefatl3task.segmentmusclefatl3task import SegmentMuscleFatL3Task